### ISSUE TITLE
Primefaces datatable with LazyDataModel is not working properly with spring session

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#1159] opened 2021-07-29 03:15 UTC
The error occurs using Primefaces datatable component with LazyDataModel and Spring Session.

I built [lazy example](https://github.com/persapiens/lazy-example) to describe it. More details about the error are at [README.](https://github.com/persapiens/lazy-example#readme)

I see that JoinFaces has `SpringSessionFixFilter` filter to enable integration between jsf and spring session. However, the error persists.

I look forward to your answer.

**Comment by persapiens** [comment] 2021-08-02 04:07
I don't if this error is related to the `SpringSessionFixFilter` filter or Primefaces itself. It happens with Primefaces 10.0 and master snapshot.

Please, could you give a hand with it @larsgrefer or @melloware ?

I really appreciate any help you can provide.

**Comment by melloware** [comment] 2021-08-02 11:37
When you say its not working what exactly is not working?

**Comment by persapiens** [comment] 2021-08-02 12:23
I've just improved the [README](https://github.com/persapiens/lazy-example#readme) to better demonstrate the problem.

In the first four steps, you can see the program running properly without spring session.

In the last six steps, you activate spring session in the example and you'll see the problem.

I don't know exactly why it is happening. I suppose that the session is not saved properly when the page is rendered in action "5- Access the program in your browser" or the session is not restored properly in action "6- Clicky any Select link in the database".

**Comment by persapiens** [comment] 2021-08-02 12:59
I've also included [primefaces-8.0 branch](https://github.com/persapiens/lazy-example/tree/primefaces-8.0) to demonstrate that the same project works with Primefaces 8.0 and spring session.

It seems that the error with spring session started with Primefaces 10.0.

**Comment by melloware** [comment] 2021-08-02 13:13
There was massive refactoring of the Datatable from 8.0-10.0 to clean up the code and resolve a lot of old issues.

I think over 150 issues closed for Datatable between 8.0-10.0.  

Also you did mention you tried 11.0.0-SNAPSHOT of PF? There were 54 more issues fixed since 10.0

https://github.com/primefaces/primefaces/issues?q=is%3Aissue+is%3Aclosed+datatable+milestone%3A11.0.0

**Comment by persapiens** [comment] 2021-08-02 14:25
The [primefaces-snapshot branch](https://github.com/persapiens/lazy-example/tree/primefaces-snapshot) shows that the same project fails with Primefaces master snapshot and spring session.

**Comment by persapiens** [comment] 2021-08-02 14:32
[Main branch](https://github.com/persapiens/lazy-example/tree/main) (using Primefaces 10.0) and [primefaces-snapshot branch](https://github.com/persapiens/lazy-example/tree/primefaces-snapshot) (using Primefaces master snapshot) use the same classes.

I changed LazyCustomerDataModel class a little because LazyDataModel load interface method changed too in [primefaces-8.0 branch](https://github.com/persapiens/lazy-example/tree/primefaces-8.0) (using Primefaces 8.0). 

Only [primefaces-8.0 branch](https://github.com/persapiens/lazy-example/tree/primefaces-8.0) works with spring session.

**Comment by melloware** [comment] 2021-08-02 14:50
The only thing I can think of is somehow with Spring Session something is not being Serialized properly when it comes to the Selection?  Looks like all of your models are Serializable so that is good.   I notice Representitive does not have a default Constructor not sure if that matters or not buts its almost like the selection can't be Serialized?

**Comment by persapiens** [comment] 2021-08-02 15:55
I've just cleaned up the example code.

I removed Representative, Country, and CustomerStatus classes. There is only Customer model class, and it has a default Constructor. 

All three branches use the same source code now.

The single difference is Primefaces version: main with Primefaces 10.0, primefaces-8.0 with Primefaces 8.0, and primefaces-snapshot with Primefaces master-SNAPSHOT.

Only the primefaces-8.0 branch works with spring session still.

**Comment by melloware** [comment] 2021-08-02 18:34
@tandraschko any thoughts on what could be wrong?  I know we made massive changes to Datable but not sure why this would have broken?

**Comment by tandraschko** [comment] 2021-08-02 18:59
No Idea sorry
Can you try to add a Integration test, so we can at least make sure it works with normal ee env?

**Comment by melloware** [comment] 2021-08-02 19:18
Yes I am pretty sure we already have an Integration Test for this and everything is working in TomEE.

**Comment by tandraschko** [comment] 2021-08-02 19:23
I can just say that for correct replication and failover, both CDI and JSF serialization must be configured

**Comment by larsgrefer** [comment] 2021-08-02 23:53
My guess would have been that the example somehow triggered reason number 4 described here: https://stackoverflow.com/a/2120183/3574494 because the serialized and re-deserialized view scoped bean isn't the __*same*__ value anymore.

But that doesn't explain why it works with PrimeFaces 8

**Comment by larsgrefer** [comment] 2021-08-03 00:13
Using spring-session-jdbc shows the same results: With Primefaces 8 the action on the viewBean is called and with Primefaces 10 it is not called

**Comment by persapiens** [comment] 2021-08-03 01:26
Using myfaces, jetty and undertow shows the same results: With Primefaces 8 the action on the viewBean is called and with Primefaces 10 it is not called.

**Comment by tandraschko** [comment] 2021-08-03 05:46
Can you fork our primefaces-test project and try to replicate? I can have a look then
And please use 11.0 Snapshot, 10 had some bugs

**Comment by melloware** [comment] 2021-08-03 11:40
@tandraschko i will create a PrimeFaces Test reproducer so we can look.  I use Selection with Lazy in all my production apps and have not noticed any issues with PF10 but maybe I am doing something different.  I will create a ticket on PF if I can reproduce it with PF Test.

**Comment by melloware** [comment] 2021-08-03 12:23
OK @persapiens I can't reproduce with a standalone reproducer.
[jf-1159.zip](https://github.com/joinfaces/joinfaces/files/6923994/jf-1159.zip)

Unzip that and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml and everything seems to be working fine.

You can run it with JSF 2.2 or Mojara/MyFaces with profiles...
```
mvn clean jetty:run -Pmyfaces22

mvn clean jetty:run -Pmyfaces23

mvn clean jetty:run -Pmojarra22

mvn clean jetty:run -Pmojarra23
```

**Comment by persapiens** [comment] 2021-08-03 17:10
You are right @melloware . In my case, the error only happens when spring session is enabled. How do we configure CDI and JSF serialization of view scoped beans in jf-1159.zip project to check if it it works with this use case?

**Comment by melloware** [comment] 2021-08-03 19:13
I could be wrong but I think JSF and CDI serialization is already enabled in that reproducer with...

```xml
    <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>server</param-value>
    </context-param>
```

**Comment by persapiens** [comment] 2021-08-03 22:39
JSF and CDI serialization is enabled in that reproducer, but is the serialization really used? Which external repository is used to serialize and deserialize the objects of the session?

In my example, I use redis as the external repository.

**Comment by tandraschko** [comment] 2021-08-04 06:56
you need
javax.faces.STATE_SAVING_METHOD=server
javax.faces.SERIALIZE_SERVER_STATE=true
org.apache.myfaces.USE_ENCRYPTION=false (easier for testing)

for OWB you dont need any setting, no idea for WELD, no idea for Spring.

then ofcouse, the container like jetty/tomcat or spring session has to serialize/deserialize. There are different mechanism available like memcached-session-manager for tomcat.

**Comment by tandraschko** [comment] 2021-08-04 10:34
also make sure your pojo implements equals/hashcode correctly

**Comment by persapiens** [comment] 2021-08-05 11:40
I think the problem is related to `javax.faces.model.ListDataModel` default constructor implementation:

```java
  public ListDataModel() {
    this(null);
  }
```

It sets list attribute to null. It seems that default constructor is always called in deserialization. So, list value is lost from the data store.

This code affects `org.primefaces.model.LazyDataModel` implementation in primefaces 10. The 10 version uses list attribute when it overrides getWrappedData() from `javax.faces.model.DataModel`.

`org.primefaces.model.LazyDataModel` in 8 version is not affected because it does not use list attribute from `javax.faces.model.DataModel`. It uses own data attribute instead. That's why 8 version is working.

I don't know if it will happen with other serialization/deserialization mechanisms, but it is happening with spring session.

**Comment by melloware** [comment] 2021-08-05 11:44
@persapiens Are you using Mojarra? It could be this issue that was recently fixed: https://github.com/eclipse-ee4j/mojarra/issues/4881

Can you try MyFaces and see if it happens?

**Comment by persapiens** [comment] 2021-08-05 13:30
Yes, I'm using Mojarra @melloware . But it fails with MyFaces also.

**Comment by melloware** [comment] 2021-08-05 13:38
Interesting I will let @tandraschko chime in...

**Comment by tandraschko** [comment] 2021-08-05 14:37
please provide a PR to restore the behavior, so we can check if all our tests are passing

**Comment by melloware** [comment] 2021-08-12 16:24
I think Thomas fixed it with this ticket: https://github.com/primefaces/primefaces/issues/7699

**Comment by t-oster** [comment] 2021-08-12 20:03
> I think the problem is related to `javax.faces.model.ListDataModel` default constructor implementation:
> 
> ```java
>   public ListDataModel() {
>     this(null);
>   }
> ```
> 
> It sets list attribute to null. It seems that default constructor is always called in deserialization. So, list value is lost from the data store.
> 
> This code affects `org.primefaces.model.LazyDataModel` implementation in primefaces 10. The 10 version uses list attribute when it overrides getWrappedData() from `javax.faces.model.DataModel`.
> 
> `org.primefaces.model.LazyDataModel` in 8 version is not affected because it does not use list attribute from `javax.faces.model.DataModel`. It uses own data attribute instead. That's why 8 version is working.
> 
> I don't know if it will happen with other serialization/deserialization mechanisms, but it is happening with spring session.

@persapiens is right with his analyzis. Here is a workaround (EDITED):
```
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import javax.faces.model.DataModelListener;
import org.primefaces.model.LazyDataModel;

/**
 * The org.primefaces.model.LazyDataModel has a deserialization problem as
 * of 10.0.0 
 * 
 * https://github.com/primefaces/primefaces/issues/7699 and
 * https://github.com/joinfaces/joinfaces/issues/1159
 * 
 * The problem is that on deserialization the default constructor on the first
 * non-serializable superclass (javax.faces.model.ListDataModel) is called,
 * which sets the list attribute (wrappedData) to null.
 * This class saves and restores it on serialization/deserialization and can
 * be used as drop-in replacement for LazyDataModel
 * @author Thomas Oster <thomas.oster@upstart-it.de>
 */
public abstract class LazyDataModelFixed<T> extends LazyDataModel<T> implements Serializable {

    private void readObject(ObjectInputStream aInputStream) throws ClassNotFoundException, IOException 
    {
        aInputStream.defaultReadObject();
        setWrappedData(aInputStream.readObject());
        setRowIndex(aInputStream.readInt());
        DataModelListener[] l = (DataModelListener[]) aInputStream.readObject();
        if (l != null) {
            for (DataModelListener li : l) {
                addDataModelListener(li);
            }
        }
    }
 
    private void writeObject(ObjectOutputStream aOutputStream) throws IOException {
        aOutputStream.defaultWriteObject();
        List wd = getWrappedData();
        if (wd != null) {
            //wrap in LinkedList because implementation may not be serializable
            wd = new LinkedList<>(wd);
        }
        aOutputStream.writeObject(wd);
        aOutputStream.writeInt(getRowIndex());
        aOutputStream.writeObject(getDataModelListeners());
    }
}

**Comment by larsgrefer** [comment] 2021-10-27 22:01
Since this is(was) an issue of PrimeFaces, im closing this here

**Closed as completed by larsgrefer** 2021-10-27 22:01 UTC
