### ISSUE TITLE
Adminfaces starter + omnifaces3.2 starter fails to start

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#547] opened 2018-09-22 12:19 UTC
Hi,

i have set up a bisc project using the dependencies adminfaces-spring-boot-starter and omnifaces3-spring-boot-starter.
SInce the last one is pulling weld the startup fails with the error:
java.lang.NoClassDefFoundError: org/jboss/logging/BasicLogger

Do i miss something?

**Comment by persapiens** [comment] 2018-09-22 12:35
Hi @Tosken1337 ,

Could you provide an example project to reproduce the error?

I look forward your answer.

**Comment by Tosken1337** [comment] 2018-09-24 15:35
I figured out that there is a missing dependency for using weld which is pulled by omnifaces dependency.
jboss-logging is missing. Maybe this dependency should be inside joinfaces weld starter?

**Comment by persapiens** [comment] 2018-10-17 14:33
Hi @Tosken1337 , we don't have any example project using `omnifaces3-spring-boot-starter` [here](https://github.com/joinfaces/joinfaces/wiki/Examples-of-JoinFaces-usage). Could you provide one?
It will became easier to reproduce the issue and provide better validation and documentation about `omnifaces3-spring-boot-starter`.

**Comment by larsgrefer** [comment] 2018-11-15 23:42
Keep in mind, that using the JoinFaces' `omnifaces3-spring-boot-starter` will also pull weld as full CDI implementation which might be unwanted in a spring-based application

**Comment by rmpestano** [comment] 2018-11-16 00:59
Hi @larsgrefer, as I'm not so familiar with Spring I don't know what kind of problems this may lead.

So considering CDI is a bad thing for Spring apps I think we can:

Disable AdminFaces control sidebar completely [here](https://github.com/joinfaces/joinfaces/blob/721f56b3759ee954b089ceb3c8eb3040596cd11e/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminConfigWrapper.java#L81) 

**OR** 

Find out the root cause of the issue https://github.com/adminfaces/admin-starter-springboot/issues/4

**Comment by persapiens** [comment] 2018-11-22 20:30
> I figured out that there is a missing dependency for using weld which is pulled by omnifaces dependency.
> jboss-logging is missing. Maybe this dependency should be inside joinfaces weld starter?

Hi @Tosken1337 ,

Done at #583 

Thank you very much.

**Comment by persapiens** [comment] 2018-11-22 20:33
> Find out the root cause of the issue [adminfaces/admin-starter-springboot#4](https://github.com/adminfaces/admin-starter-springboot/issues/4)

Hi @rmpestano ,

The error occurs when any of the following `p:selectBooleanCheckbox` are clicked at [admin.xhtml](https://github.com/adminfaces/admin-template/blob/4c075308caede385b1bc27610c8d064fa0bad9c6/src/main/resources/META-INF/resources/admin.xhtml#L201) and [admin-top.xhtml](https://github.com/adminfaces/admin-template/blob/4c075308caede385b1bc27610c8d064fa0bad9c6/src/main/resources/META-INF/resources/admin-top.xhtml#L200): "Fixed Layout", "Boxed Layout", "Collapsed Sidebar", "Sidebar Expand on Hover", "Control Sidebar fixed" and "Dar Sidebar Skin". All of them are implemented the same way, using p:ajax
```xml
<p:ajax update="@none" global="false" listener="#{layoutMB.toggleControlSidebarSkin()}" partialSubmit="true"/>
```

It works when I remove this [p:ajax code.](https://github.com/adminfaces/admin-template/blob/4c075308caede385b1bc27610c8d064fa0bad9c6/src/main/resources/META-INF/resources/admin.xhtml#L201) I've tested with `omnifaces1-spring-boot-starter` and using `spring boot jar packaging`.

PS: I would not say that CDI is a bad thing for Spring apps, but unfortunatelly they are not completely integrated yet. If you want to read more about Spring and Full CDI integration, please look at #187 . This issue resulted `weld-spring-boot-starter`.

**Comment by persapiens** [comment] 2018-11-30 17:05
I think we can close it now. If you have any comments, reopen this issue or open another one.

**Closed by persapiens** 2018-11-30 17:05 UTC
