### ISSUE TITLE
cdi-api not pulled by jsf-spring-boot-starter

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#503] opened 2018-06-19 19:51 UTC
Starting with `joinfaces 3.2.2`, `javax.enterprise:cdi-api` library is not pulled by default. The change was done in [this PR](https://github.com/joinfaces/joinfaces/pull/485).

So, if the project wants to use `javax.inject.Named` or `javax.inject.Inject` classes, it has to add the dependency now.

Is this the desired behavior?

**Comment by larsgrefer** [comment] 2018-06-19 20:15
The `cdi-api` is only required for myfaces, so its only pulled for myfaces.

**Comment by larsgrefer** [comment] 2018-06-19 20:46
In #485 I've revisited, which components and component-combinations need which dependencies.
As part of this process, some non-required dependencies got removed.

One of this non-required dependencies is CDI (and it's api in particular).

Instead of `@Named` and `@Inject` one can simply use `@Component` and `@Autowired`.

If one still want's to use these annotations, one can follow the documentation here: https://docs.spring.io/spring-framework/docs/5.0.x/spring-framework-reference/core.html#beans-standard-annotations

**Comment by larsgrefer** [comment] 2018-06-19 20:48
IMHO the `cdi-api` is not important for a normal spring application, so there is no justification to provide it as default dependency.

What do you think about this?

**Comment by persapiens** [comment] 2018-06-19 21:14
> the cdi-api is not important for a normal spring application

joinfaces apps are jsf application also and `cdi-api` is popular (but not required) in this environment. However, I agree with you and I think the app should be shorter as possible too. 

PS.: I forgot that adminfaces requires cdi-api. That's why I created PR #504

**Comment by WalterMourao** [comment] 2018-06-20 12:47
Hi folks. I understand about @Named and @Inject but, how about @SessionScoped? "javax.faces.bean.SessionScoped" is deprecated...

**Comment by mtbadi39** [comment] 2018-06-20 13:47
Yes @WalterMourao 
I just updated a project and noticed that "javax.faces.bean.SessionScoped" is deprecated... :confused:

**Comment by larsgrefer** [comment] 2018-06-20 16:02
@WalterMourao @mtbadi39 `org.springframework.web.context.annotation.SessionScope` is the spring-way of defining session scoped beans.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/annotation/SessionScope.html

**Comment by larsgrefer** [comment] 2018-06-20 16:06
We haven't changed our cdi support. You can just add a dependency on `cdi-api` and your code will work the same way it did before.

**Comment by WalterMourao** [comment] 2018-06-20 16:44
@larsgrefer thank you. Spring's session scope is fine (I'm not experienced with spring web).

**Comment by larsgrefer** [comment] 2018-06-20 22:37
I've updated the project wiki to list all possible scope annotations: https://github.com/joinfaces/joinfaces/wiki/JSF-and-CDI-annotations-support

**Comment by larsgrefer** [comment] 2018-06-22 23:15
I think all questions here are answered, so im closing this issue.

**Closed by larsgrefer** 2018-06-22 23:15 UTC

**Comment by stochmalm** [comment] 2018-07-04 07:19
I changed my annotations to spring ones and when I run app from maven (spring-boot:run) I got this exception:
`java.lang.NoClassDefFoundError: javax/enterprise/context/spi/Contextual
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_152]
	at com.sun.faces.util.Util.loadClass(Util.java:333) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.ApplicationConfigProcessor.addSystemEventListener(ApplicationConfigProcessor.java:1032) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.ApplicationConfigProcessor.process(ApplicationConfigProcessor.java:370) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:155) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:138) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:155) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:246) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:443) ~[javax.faces-2.3.5.jar:2.3.5]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:237) [javax.faces-2.3.5.jar:2.3.5]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: javax.enterprise.context.spi.Contextual
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	... 20 more`

Do I really need to provide CDI dependency?

joinfaces-parent 3.2.3,
Spring Boot v2.0.3.RELEASE, Spring v5.0.7.RELEASE,
Mojarra.
