### ISSUE TITLE
Injectable PrimeFaces

### ISSUE THREAD

**Issue by melloware** [joinfaces/joinfaces#633] opened 2019-01-16 20:33 UTC
PrimeFaces right now is a static utility similar to FacesContext you use it like PrimeFaces.current();

Submitting a PR to make it Autowirable to make injection and unit testing easier.

This will allow

```java
   @Autowired
   PrimeFaces primefaces;
```

**Comment by larsgrefer** [comment] 2019-01-16 23:53
There is no need to open a separate issue if you're going to open a corresponding pull request.

So I'm closing this as a duplicate of #634

**Closed by larsgrefer** 2019-01-16 23:53 UTC

**Comment by melloware** [comment] 2019-01-17 00:41
My apologies. I am a committer on Primefaces project and the policy is no PR is accepted without a corresponding issue ticket explaining the reason for the PR so it can be labeled with a version for release notes. 

In the future I will just submit a PR.
