### ISSUE TITLE
IOException: Broken pipe

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#418] opened 2018-03-11 10:33 UTC
Just rewrote my JSF template to use Spring Boot 2 and tought I would test joinfaces and seems to be working good.. :)
But I get this IOException sometimes when I start my application (see subject) but the application seems to work though.
I also get this in my log:

JSF1064: Unable to find or serve resource, fa/fontawesome-webfont.woff2, from library, primefaces
(the resource it complains about can change)

Is this a joinfaces problem or something else? (I have upgraded from Spring Boot 1.x to 2, PF 6.1.x to 6.2, JSF 2.2.x to 2.3, etc so not sure where to start looking...)

**Comment by persapiens** [comment] 2018-03-11 12:52
hi @bjorntj ,

Could you try current joinfaces snapshot please? I think this problem is fixed [here](https://github.com/joinfaces/joinfaces/pull/415).

I look forward your answer.

**Comment by bjorntj** [comment] 2018-03-11 12:54
Actually, I am using Undertow at the moment but same issue?

**Comment by persapiens** [comment] 2018-03-11 13:40
Could you provide example project?

**Comment by bjorntj** [comment] 2018-03-11 14:37
I can see what I can do... Problem is that this does not happend very often...

**Comment by persapiens** [comment] 2018-03-11 15:39
Ok. I will wait your feedback.

**Comment by bjorntj** [comment] 2018-03-12 08:21
Here is a small sample project but not sure if you will be able to provoke the same error... But at least you see how I configured my project...
[joinfacestest.zip](https://github.com/joinfaces/joinfaces/files/1801891/joinfacestest.zip)

**Comment by larmic** [comment] 2018-03-12 09:00
@bjorntj maybe you could create a simple github demo project? I don't like download and extract zip files :)

**Comment by persapiens** [comment] 2018-03-12 18:25
@bjorntj, your demo project seems working.

**Comment by bjorntj** [comment] 2018-03-12 18:33
Yes, and so does my other project... The error just comes in special circumstances it seems...

**Comment by larsgrefer** [comment] 2018-04-04 21:54
@bjorntj Can you please provide the full stacktrace of the exception?

**Comment by bjorntj** [comment] 2018-04-05 08:50
Not sure if I can find the exception anymore.. Also I have not seen this exception in my projects since I created this issue...

**Comment by persapiens** [comment] 2018-04-05 11:59
@bjorntj, do you mind closing this issue? You can reopen it when the error appears again.

**Closed** 2018-04-05 12:01 UTC
Labels: waiting-user-feedback

**Comment by schicho** [comment] 2022-03-21 17:29
Can this be reopened?

I am currently dealing with this issue.

I am using joinfaces version 4.5.0.

I will try to describe it:
- It's a Firefox only issue. Requests are sent for potentially cached files. If the cached file is found before the http answer is received the connection is aborted. Thus leading to a `ClientAbortException`.
- https://forum.primefaces.org/viewtopic.php?f=48&t=55047&start=10 The problem is also described here
- MyFaces has fixed this in their ResourceHandlerImpl. They just catch the exception in the method `handleResourceRequest(...)` and log it. See patch https://issues.apache.org/jira/browse/MYFACES-3736
- JoinFaces does not use MyFaces' ResourceHandlerImpl, but the one from the package `com.sun.faces.application.resource`. They don't catch the exception here and just continue to throw it, which leads to a StackTrace print.

Can I somehow use a different ResourceHandlerImpl in my application? Like choosing the one used in MyFaces?
Or would this need to be configured in code in JoinFaces itself?

------
Edit:

Link to the implementation in [MyFaces](https://github.com/apache/myfaces/blob/c2d9da89acd23cbf9f96d7a3dab9e72654142237/impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java#L608).

**Comment by larsgrefer** [comment] 2022-03-22 00:14
@schicho If you think this is an error in Mojarra, you can report it here: https://github.com/eclipse-ee4j/mojarra/issues

You can use Joinfaces with MyFaces instead of Mojarra. This is explained here: https://docs.joinfaces.org/4.5.x/reference/#_example_using_myfaces_instead_of_mojarra

**Comment by schicho** [comment] 2022-03-22 16:44
Thank you for your response.

It has been listed as an issue multiple time already for Mojarra. [Here](https://github.com/eclipse-ee4j/mojarra/issues/4280) it is described in detail and there is also a workaround described by BalusC, for anyone else having this issue.

Maybe I will do a PR... Anyway, my current solution was to just switch to MyFaces, which solved it immediately.
