### ISSUE TITLE
https://joinfaces-example.herokuapp.com/fileUpload.jsf example not working

### ISSUE THREAD

**Issue by aspirations** [joinfaces/joinfaces#886] opened 2021-04-05 05:37 UTC
@melloware  Can you please check this when even I am downloading it is showing 0KB

**Comment by melloware** [comment] 2021-04-11 12:32
I will see if I can look into this.

**Comment by melloware** [comment] 2021-04-11 12:45
@aspirations I think the issue is that if you look at the PrimeFaces Showcase:
https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml?

The bean is `@RequestScoped` and you use the `UploadFile` value and then its done. the JoinFaces example is `@ViewScoped` and marks the bean `transient` but I don't think you can use the `UploadFile` this way.  So I am pretty sure that is the problem.

**Comment by melloware** [comment] 2024-06-12 01:44
@aspirations this can be closed

**Comment by aspirations** [comment] 2024-06-12 04:37
Yes you can close. Thank You

**Comment by melloware** [comment] 2024-06-12 09:05
You opened the ticket I think you are the only one with permission to close it

**Closed** 2024-06-12 09:12 UTC
